### ISSUE TITLE
JSON word lists

### ISSUE THREAD

**Issue by spacehuhn** [GlOwl/hackerman#5]
Save nouns, adjectives and verbs in JSON files instead of python files.

**Comment by KwameTaylor** [comment]
@GlOwl I'd be happy to take this issue, just lmk :)

**Comment by GlOwl** [comment]
Thanks, just make a pullrequest if you have something.

**Comment by KwameTaylor** [comment]
Awesome, just about to PR with the nouns json.

**Comment by KwameTaylor** [comment]
I can do the other lists later today, but wanted to make sure with you @GlOwl that it was formatted how you need before I moved on. Let me know. Hopefully I tagged the issue right, btw. I'm somewhat new to this. 😅
